# Generated by Django 4.1.7 on 2023-04-24 20:53

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_panel', models.BooleanField(default=False)),
                ('local_control_panel', models.BooleanField(default=False)),
                ('startup_works', models.BooleanField(default=False)),
                ('mounting_kit', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Complectation',
                'verbose_name_plural': 'Complectation',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('screen', 'Screen'), ('scraper', 'Scraper'), ('suction_scraper', 'Suction scraper'), ('penstock', 'Penstock')], max_length=255)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('power', models.FloatField(default=0)),
                ('complectation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='projects.complectation')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=projects.models.get_file_path)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Manufacture',
                'verbose_name_plural': 'Manufactures',
            },
        ),
        migrations.CreateModel(
            name='TechnologicalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('node_number', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='projects.location')),
            ],
            options={
                'verbose_name': 'Technological node',
                'verbose_name_plural': 'Technological nodes',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='projects.equipment')),
                ('technological_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.technologicalnode')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.manufacture'),
        ),
    ]
