# Generated by Django 4.1.7 on 2023-12-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('not_started', 'Not started')], default='not_started', max_length=128),
        ),
    ]
