#version: '3'
#
#services:
#  web:
#    build: .
#    restart: always
#    command: sh -c "python3 manage.py collectstatic --noinput &&
#                    python3 manage.py migrate &&
#                    gunicorn ecopol.wsgi -c deploy_config/gunicorn.cfg --reload"
#    volumes:
#      - static_vol:/ecopol/static
#      - media_vol:/ecopol/media
#    expose:
#      - 8000
#    env_file:
#      - .env
#    networks:
#      - nginx_network
#
#  nginx:
#    build: ./nginx
#    ports:
#      - "80:80"
#    depends_on:
#      - web
#    volumes:
#      - nginx_network:/ecopol/nginx
#      - static_vol:/ecopol/static
#      - media_vol:/ecopol/media
#    networks:
#      - nginx_network
#
#volumes:
#  nginx_network:
#  static_vol:
#  media_vol:




version: '3'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/ecopol
      - ./static:/ecopol/static
    entrypoint: ./entrypoint.sh
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - nginx_network

  nginx:
    image: nginx:1.15.9
    ports:
      - "90:90"
#      - "443:443"
    depends_on:
      - web
    volumes:
      - "./deploy_config/nginx/staging:/etc/nginx/conf.d"
      - "./static:/ecopol/static"
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - nginx_network

networks:
    nginx_network:
