version: '3.4'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/ecopol
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db


  db:
    image: postgres:14.0
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} || exit 1
    volumes:
      - ecopol_db:/var/lib/postgresql/data
    restart: on-failure
    env_file:
      - .env
    expose:
      - 5432


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


volumes:
  ecopol_db:
