version: '3.4'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/ecopol
    command: sh -c "python3 manage.py collectstatic --noinput &&
                    python3 manage.py migrate &&
                    python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db


  db:
    image: postgres:14.0
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} || exit 1
    volumes:
      - ecopol_db:/var/lib/postgresql/data
    restart: on-failure
    env_file:
      - .env
    expose:
      - 5432

  celery:
    build:
      context: .
    env_file: .env
    command: celery -A ecopol worker -l info -P threads
    expose:
      - 6379
    depends_on:
      - redis
      - db

  redis:
    image: redis
    restart: on-failure

  flower:
    build: ./
    command: celery -A celery flower
    volumes:
      - ./flower:/data
    working_dir: /data
    env_file:
      - .env
    ports:
      - 5555:5555
    depends_on:
      - celery
      - redis

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


volumes:
  ecopol_db:
