version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/ecopol
    command: gunicorn ecopol.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db


  db:
    image: postgres:14.0
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} || exit 1
    volumes:
      - ecopol_db:/var/lib/postgresql/data
    restart: on-failure
    env_file:
      - .env
    expose:
      - 5432


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  nginx:
    build: nginx
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  ecopol_db:
