version: '3'

services:
  web:
    build: .
    restart: always
    container_name: django_app
    command: sh -c "python3 manage.py collectstatic --noinput &&
                    python3 manage.py migrate &&
                    python3 manage.py runserver"
#    volumes:
#      - static_vol:/ecopol/static
#      - media_vol:/ecopol/media
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/sites-available:ro
    ports:
      - "90:90"
    depends_on:
      - web
    networks:
      - nginx_network
#  nginx:
#    build: ./nginx
#    ports:
#      - "90:90"
#    depends_on:
#      - web
#    volumes:
#      - static_vol:/ecopol/static
#      - media_vol:/ecopol/media
#    networks:
#      - nginx_network

volumes:
  static_vol:
  media_vol:

networks:
    nginx_network:



#version: '3'
#
#services:
#  web:
#    build: .
#    restart: always
#    volumes:
#      - .:/ecopol
#      - ./static:/ecopol/static
#    entrypoint: ./entrypoint.sh
#    expose:
#      - 8000
#    env_file:
#      - .env
#    networks:
#      - nginx_network
#
#  nginx:
#    image: nginx:1.15.9
#    ports:
#      - "90:90"
##      - "443:443"
#    depends_on:
#      - web
#    volumes:
#      - "./deploy_config/nginx/staging:/etc/nginx/conf.d"
#      - "./static:/ecopol/static"
#      - /etc/letsencrypt:/etc/letsencrypt:ro
#    networks:
#      - nginx_network
#
#networks:
#    nginx_network:
