version: '3.8'

services:
  web:
    build: .
    restart: always
    container_name: django_app
    command: sh -c "python3 manage.py collectstatic --noinput &&
                    python3 manage.py migrate &&
                    gunicorn ecopol.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
        - static_volume:/home/app/web/static
        - media_volume:/home/app/web/media
    env_file:
      - .env


  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:

#version: '3'
#
#services:
#  web:
#    build: .
#    restart: always
#    volumes:
#      - .:/ecopol
#      - ./static:/ecopol/static
#    entrypoint: ./entrypoint.sh
#    expose:
#      - 8000
#    env_file:
#      - .env
#    networks:
#      - nginx_network
#
#  nginx:
#    image: nginx:1.15.9
#    ports:
#      - "90:90"
##      - "443:443"
#    depends_on:
#      - web
#    volumes:
#      - "./deploy_config/nginx/staging:/etc/nginx/conf.d"
#      - "./static:/ecopol/static"
#      - /etc/letsencrypt:/etc/letsencrypt:ro
#    networks:
#      - nginx_network
#
#networks:
#    nginx_network:
