version: '3'

services:
  web:
    build: .
    restart: always
    volumes:
      - static_vol:/ecopol/static
      - media_vol:/ecopol/media
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - nginx_network:/ecopol/nginx
      - static_vol:/ecopol/static
      - media_vol:/ecopol/media

volumes:
  nginx_network:
  static_vol:
  media_vol:
